### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by ocrhell** [xulihang/ImageTrans-docs#432] opened 2023-06-14 21:24 UTC
This piece of software is great with the exception of it being extremely buggy.

What I'm trying to do: Japanese, vertical text -> English, horizontal text
OS: Windows 11

1) "Detect areas and recognize text"
This works nicely, but sometimes it misses a portion of the text. Sure, I can fix it manually but there's another problem.

2) "Translate all text areas"
The translated text only fits the size of the detected boxes in 1). This results in a messy combination of vertical English letters. I have to manually typeset the box in order to fix that and make it into readable English. It becomes a pain when you have over 100 pictures to do this for.

The masking feature with LamaInpaint is also a nice addition but for it to work properly, I have to create a mask and then edit the text-removed image manually because the algorithm is set for telea. Otherwise the masking part doesn't look polished if I select LamaInpaint as the default text-removal tool in Project>Settings. Again, it becomes a pain when I have over 100 pictures.

The server addition doesn't work for me at all. ImageTrans_wsServer is in the same folder as ImageTrans. The Chrome extension is installed. When I follow the steps exactly from https://github.com/xulihang/ImageTrans_chrome_extension
I always get a "Failed to connect to ImageTrans server". Tools>Server>Start the server>Reconnect is always "Disconnected".

In terms of bugs, the program sometimes crashes or stops functioning without reason. For example, if I create a mask, go to text removal and then go back to mask, I am met with a blank screen and the program ceases to function. It's not frozen, but functionality becomes nonexistent. During processing, it sometimes freezes completely. In order to guarantee a successful run, each step has to be precise otherwise it'll eventually crash somewhere.

Are you familiar with the Chrome extension "Ichigo Manga Translator"? Personally, it also is great on-the-fly translator, but what it's lacking is parameter/settings modification. I'd love to have the same automation of it but with the ability to tweak the settings for my needs. I am 100% certain that the output from ImageTrans is much more refined but as a current amateur user, I am unable to reproduce something similar to Ichigo Manga Translator.

**Comment by xulihang** [comment] 2023-06-15 04:28
ImageTrans is designed to translate any images. So its default configuration is not optimized for manga.

There are somethings you can to do optimize it for translating Japanese manga to English:

1. Use balloon detection + mangaOCR or mangaTranslator which have a better accuracy and work offline. Check out [this blog](https://www.basiccat.org/best-practice-manga-ocr-and-translation/) for more.
2.  Enable converting vertical to horizontal for better layout as discussed here: https://github.com/xulihang/ImageTrans-docs/issues/190
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/cb8cf67a-c3b6-4ec5-b591-1ad69140e743)

**Comment by xulihang** [comment] 2023-06-15 04:32
About setting Lama Inpaint as the default, I am not sure what the problem is. If you set it in the settings, telea will not be used when generating mask and text-removed images by checking "Translated" or using batch operations.

**Comment by xulihang** [comment] 2023-06-15 04:35
In case of crashes, I rarely meet crashes. Please give me exact steps to reproduce the problem.

As for starting the server, you have to use JRE11. The easiest way is to use the full version from onedrive and let the program download and start the server.

**Comment by ocrhell** [comment] 2023-06-17 23:04
So after tinkering a bit with what you've suggested, I've managed to reach about 80% satisfaction. I have installed these plugins so far:

- LamaInpaint
- MangaTranslator
- Sugoi Translator

This is the current workflow:  
-> db+resnet (MangaTranslator) [OCR] 
-> sugoi [translation] 
-> LamaInpaint [mask]

The problems I'm currently facing are: When the translated text has apostrophes (') or emojis from sugoi, it gets replaced by \u2019 (for apostrophes) and similarly \u[NUMBER] for emojis. It doesn't always replace apostrophes with \u2019, but it does happen for some reason. Checking sugoi, it has no issues with apostrophes or emojis.

The other problem was mentioned here https://github.com/xulihang/ImageTrans-docs/issues/190
Depending on the bubble size, the generated text sometimes barely fills the bubble and if I do increase the font size, some complete words spread into two sentences like so:
HOSPI
TAL

I'd like to fit the bubble with text as much as possible without sacrificing word integrity. Is there an automated workaround for this?

**Comment by xulihang** [comment] 2023-06-18 03:04
1. You can enable AutoCorrect to replace characters for machine translation. If this is not enough, I have to update the Sugoi Translator's plugin to do this.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/4a92ed06-4a75-4411-87fa-2ea5d73926e3)

2. Breaking words where there is not enough space is the default behavior of the underlying text engine. The text engine is a built-in one in JavaFX which does not give me many controls. I have to implement my own text engine for such a purpose.

**Comment by ocrhell** [comment] 2023-06-24 18:39
Great. I'll just wait for updates. In the meantime, I don't see this https://github.com/xulihang/ImageTrans-docs/issues/413 in "Default mask generation method". I am on 1.9.8.

**Comment by xulihang** [comment] 2023-06-25 04:21
Check if there is the `InsetRectMaskGenPlugin.jar` file in the plugins folder.

Try to use `ImageTrans.bat` to start the program which has a larger memory setting for Java.

**Comment by ocrhell** [comment] 2023-06-25 05:14
It's not in the plugins folder. I'm assuming this hasn't been updated https://github.com/xulihang/ImageTrans_plugins/releases/tag/plugins

Same issue with `ImageTrans.bat`. Still displays an empty window. Sometimes after a couple of tries and sometimes instantly. Maybe it's the amount of files in a project? Don't think it's my hardware either. 5900X, 64GB RAM.

**Comment by xulihang** [comment] 2023-06-27 04:17
I have updated the plugins zip file.

I will try to fix the issues. As for the crashing, are you using the x86 version or the x64 version? Could you send me some image files so that I can reproduce the problem?

**Comment by ocrhell** [comment] 2023-06-27 13:31
Thank you.

I'm using the x64 version. Here, this is one of them

![get0001](https://github.com/xulihang/ImageTrans-docs/assets/136637583/99e1f127-a8b3-4510-8b9a-4eaee54638db)


https://github.com/xulihang/ImageTrans-docs/assets/136637583/e73b3510-5165-49f5-a8c7-08a20bfc0d69


It might have something to do with the resolution of an image or the scale or a combination of both.

**Comment by xulihang** [comment] 2023-06-28 12:26
I see. The image has a large resolution. Actually, ImageTrans will scale down images if their width or height is over 8000. It seems that it needs a smaller threshold.

The error should be related to the limitation of JavaFX's canvas:

```
java.lang.NullPointerException
	at com.sun.javafx.sg.prism.NGCanvas.handleRenderOp(NGCanvas.java:1353)
	at com.sun.javafx.sg.prism.NGCanvas.renderStream(NGCanvas.java:1103)
	at com.sun.javafx.sg.prism.NGCanvas.renderContent(NGCanvas.java:609)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2294)
	at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2188)
	at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2214)
	at com.sun.javafx.sg.prism.CacheFilter.impl_renderNodeToCache(CacheFilter.java:671)
	at com.sun.javafx.sg.prism.CacheFilter.render(CacheFilter.java:575)
	at com.sun.javafx.sg.prism.NGNode.renderCached(NGNode.java:2358)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2044)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:235)
	at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:577)
	at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2053)
	at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1945)
	at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:477)
	at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:330)
	at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xulihang** [comment] 2023-06-28 12:33
I can send you an interval version to have a test. You can send a mail to me and I will send you the file to update: <admin@basiccat.org>

**Comment by xulihang** [comment] 2023-06-29 04:34
I've sent you the file via gmail. Please try it out.

**Comment by xulihang** [comment] 2023-06-30 04:13
The current performance of handling huge images is not very good. I have to restructure the mask editor based on projects like this one: [HugeImageView - show very large images](https://www.b4x.com/android/forum/threads/b4x-hugeimageview-show-very-large-images.132905/)

**Comment by ocrhell** [comment] 2023-06-30 06:08
Is there no temporary fix at the moment?

**Comment by xulihang** [comment] 2023-06-30 06:37
Shrinking the image in the mask editor works in my case.

You can also use a third-party image editor to remove the text and save the image with the `-original.png` suffix so that ImageTrans will use it as the text-removed image.

**Comment by ocrhell** [comment] 2023-06-30 12:15
It's a hit and miss on my end. Sometimes it works once but then when I try to edit the mask again, it crashes. Sometimes it just never shows up.

I wouldn't mind the image to be shrunken down during mask editing. In fact, I prefer that. Is there a way to default to a specific scale percentage when I open mask editing instead of always launching at 100%? Would also like that functionality for initially loaded images as well, if possible.

**Comment by xulihang** [comment] 2023-07-01 07:49
The current mask editor will set the percent to 100% after clicking the save button which may cause your crashing problem, so setting the default percent will not solve the crashing problem.

About saving the previous settings like display percentage, enabled check boxes, it is a troublesome work and not in high priority. I will try to implement it when I have time.

**Comment by xulihang** [comment] 2023-07-02 03:25
> Another issue is the overflow of text from translated pictures. The software doesn't tell you if you're going out of the boundaries of an image. I have translated pictures that have an extra 2 pixels to the right/left/up/down in their resolutions because of this.

This issue is solved in 2.0.0. Check out this to learn more: https://github.com/xulihang/ImageTrans-docs/issues/452

**Comment by ocrhell** [comment] 2023-08-06 02:55
Checking in a month later.

Thanks for the fix. I see that there have been a couple of updates since. My biggest issue is the crashing with the mask editor. Has it been resolved or is it still a work in progress?

**Comment by xulihang** [comment] 2023-08-06 04:08
The solution for editing a large image's mask now is this:

1. Generate the mask images first.
   ![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/3ed5dea2-081b-4520-b2d4-3c92b04ade49)
2. Edit the mask of a small area.
   ![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6af4716b-3ece-4208-8695-910a0c7a2170)

**Comment by ocrhell** [comment] 2023-08-21 15:09
Hello, can you please explain this error
```
error: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]
StackTrace: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
]
	at org.opencv.core.Core.addWeighted_1(Native Method)
	at org.opencv.core.Core.addWeighted(Core.java:1038)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at anywheresoftware.b4j.object.JavaObject.RunMethod(JavaObject.java:132)
	at org.xulihang.imagetrans.cv2._addweighted(cv2.java:71)
	at org.xulihang.imagetrans.utils$ResumableSub_inpaintByBox.resume(utils.java:2617)
	at anywheresoftware.b4a.BA.checkAndRunWaitForEvent(BA.java:136)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:85)
	at anywheresoftware.b4a.BA.raiseEvent(BA.java:78)
	at anywheresoftware.b4a.keywords.Common$3.run(Common.java:1086)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by xulihang** [comment] 2023-08-21 15:19
The inpainted image's size does not match the original one.

**Comment by ocrhell** [comment] 2023-08-21 18:17
I just checked. The generated "-mask" image matches the resolution of the original image. It just refuses to generate the "-text-removed" image.

**Comment by ocrhell** [comment] 2023-08-24 12:41
So this isn't an issue but more of a how. 

Google Lens provides a more accurate OCR result in some of the cases after testing it out. I don't know how many times I can do it manually before it runs out and it requires me to pay up, but is there a way to integrate that? Is there an alternative way than signing up for their cloud platform?

**Comment by ocrhell** [comment] 2023-08-25 00:50
Works like a charm. Thanks.

Some new issue I'm facing:

- Font styling. If the image is scaled down with the magnifier during editing and I enable "Stroke" with a value of, let's say 20, a big white box surrounds the text area. This doesn't become true when I scale it back to the original size. Even the rendered image doesn't have that big white box. This brings me to the next problem.
- If the white box is visually outside the image border during editing but the _**text is still within the border of the image**_, the rendered image has the same resolution as the original image however, the rendered image itself still shifts the amount of pixels that the white box is crossing out of the image border during editing. So the contents of the image are shifted either horizontally/vertically, but the resolution of original/rendered match.
- Font styling again. When editing an image with a lot of text areas, if I select all text areas and try to apply a specific size/type/color etc... for the text, it only affects one text area. Would be nice to be able to modify the styling for all the text areas all at once. 
- The detect font color doesn't seem to be accurate when the text is colored and each letter is surrounded by a white border ie. Stroke. It is sometimes able to correctly detect the color, but other times it detects the stroke color.

**Comment by xulihang** [comment] 2023-08-25 04:25
1. You have to press okay to save the editing before changing the display percentage. 
    ![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/bce9c7ee-1630-41b0-b70f-04af641c9606)
2. I don't quite understand the problem. If the textbox is outside of the image, the part outside will be cut off. You can enable the following project setting to automatically adjust the text boxes.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/2c148d8b-0812-4bb0-a043-e2a52745de1b)
3. I will try to add an "apply to all" option.
4. You can try to use manga-image-translator to detect the color according to this: https://github.com/xulihang/ImageTrans-docs/issues/478

**Comment by ocrhell** [comment] 2023-08-25 08:40
1.
https://github.com/xulihang/ImageTrans-docs/assets/136637583/880af5d9-76cc-4fac-9f01-c138d5221cab

This is obviously an extreme example with 100 stroke, but it happens with lower resolution images as well.

2. Original image
![get0001](https://github.com/xulihang/ImageTrans-docs/assets/136637583/cfbcd58e-dbb1-45c0-a314-8b67922661c8)

Rendered image
![get0001](https://github.com/xulihang/ImageTrans-docs/assets/136637583/2d1b7de8-4f78-4f0b-bfc9-bb4a59899ab2)

Notice that the resolution is the same but the contents of the image are shifted.

Also, stroke doesn't scale properly with the resolution of an image. If I set 100 for lower resolution images, it would probably cover the entire image. Is there a way to make the stroke output visually the same for every possible resolution? Manually doing it for every image gets tedious.

**Comment by xulihang** [comment] 2023-08-26 04:56
I've fixed this issue by setting the stroke to the text only instead of the container of the text.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/40a26afa-e441-421a-b299-838a08dd2d57)

**Comment by xulihang** [comment] 2023-08-26 08:48
> Works like a charm. Thanks.
> 
> Some new issues I'm facing:

These issues are solved in v2.4.0

**Comment by ocrhell** [comment] 2023-08-27 00:00
The overflow problem works great, thanks.

The Font toolbar works nicely for type/size/alignment/color etc..., but the text areas are still treated individually when trying to apply a fixed Stroke value. This is the error I get:

```
error: java.lang.Exception: Sub switchimage signature does not match expected signature.
StackTrace: java.lang.Exception: Sub switchimage signature does not match expected signature.
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:93)
	at anywheresoftware.b4a.keywords.Common.CallSub4(Common.java:487)
	at anywheresoftware.b4a.keywords.Common.access$0(Common.java:467)
	at anywheresoftware.b4a.keywords.Common$CallSubDelayedHelper.run(Common.java:541)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

``` 

Even with this popup however, only one text area gets the specified Stroke value applied.

Also, I have come to realize that Microsoft PowerToys offers a Text Extractor based on this project:
https://github.com/TheJoeFin/Text-Grab

I am not well-versed in the capabilities of this software, but it is another OCR method to look into if it's possible to integrate of course.

**Comment by xulihang** [comment] 2023-08-27 02:50
I've fixed the bug and the styles can be applied to all boxes now. Please download v2.4.0 again.

But it is recommended to use a global style to set stroke for multiple images.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/e2cb1446-a044-4559-b66c-e865f17061d3)

**Comment by xulihang** [comment] 2023-08-27 02:54
https://github.com/TheJoeFin/Text-Grab
This project is using Windows' built-in OCR which is called WinRT in ImageTrans.

**Comment by ocrhell** [comment] 2023-08-27 11:07
Works perfectly. Thanks.

WinRT produces characters separated by spaces for some reason. PowerToys doesn't have that issue.

Also I'm grateful for the server that you've provided for google drive, but is it currently operating? I'm getting no outputs at all. On the previous version of ImageTrans it was fully operational.

**Comment by xulihang** [comment] 2023-08-27 12:54
WinRT's raw results contains spaces. You can check the "Remove spaces" to remove them.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/72dbfbf8-dd57-45bf-8438-309941108b46)

Removing spaces is not effective using "detect text areas and recognize text". You can to perform boxes merging to remove spaces.
![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/c21f0e69-4634-4c2a-90ed-30cc24d4cf68)

**Comment by xulihang** [comment] 2023-08-27 12:55
Google drive's token expires every 7 days.

You have to wait for me to reset the token or run it by yourself.

**Comment by ocrhell** [comment] 2023-08-27 23:38
Great.

I wouldn't mind running it myself. Is there a somewhat user-friendly guide for that?

**Comment by xulihang** [comment] 2023-08-28 04:30
You can follow this guide: https://github.com/xulihang/ImageTrans-docs/issues/91#issuecomment-950313389

It may be a bit complex.

**Comment by ocrhell** [comment] 2023-08-28 04:57
I'm not sure I get it. I have followed those exact steps and have it running this way already. However, what I'm getting confused about is even with these steps, I'm relying on your server, correct? If yes, then my question is how can I run my own server independently?

**Comment by xulihang** [comment] 2023-08-28 05:12
The version above is the command line version which directly runs on your device.

**Comment by ocrhell** [comment] 2023-08-28 08:51
Got it running. Now the portion that I'm trying to OCR gets uploaded as a document to my google drive and returns the text in the software. Works nicely. Thanks.

**Comment by ocrhell** [comment] 2023-08-30 09:05
So the "Apply to all" function in the Font tab overrides the font color after using it once and then unchecking it. So if I decide to detect the color of a text area and apply that color to that one text area, all other text areas get that color. I think it only happens if I modify the Stroke value for all text areas all at once.

I'm not sure if I'm unable to figure it out, but is there a way to batch export images in PNG? Because currently I can only do that individually as far as I can tell.

**Comment by xulihang** [comment] 2023-08-30 13:36
If the original image format is PNG, it will output PNG. If the original format is JPEG, it will output JPEG. Currently, there are no settings to specify the batch output image format.

**Comment by ocrhell** [comment] 2023-09-06 00:10
So after using the program consistently for the past 4 days, these are the remaining wants/fixes for my use-case that I hope will also benefit others.

Fixes:
- Mask editing crash with larger images
- Font, "apply to all" is a bit buggy when trying to change color of text areas individually after using it once
- Font, if I pick a color before checking translated box and then check the box, I can no longer drag to modify the font size during typesetting. I have to manually increase/decrease the size in the font tab
- Holding "Shift" to maintain aspect ratio of current text box is great, but sometimes the text doesn't maintain the same ratio and a word or two get slightly shifted inside
- Not sure if it's a JPEG limitation, but some text colors look washed out even if I set the output to 100. PNG doesn't have that problem. Also, the translated file size is always smaller than the original image

Wants:
- Custom font colors are saved in project. I always have to re-add them when I re-open a project
- More shortcuts. 
           - Would like to be able to precisely shift and move a text box using the keyboard keys
           - Increase/decrease font size with keyboard/mouse or keyboard only
           - Expand/shrink side panel with keyboard
- Hide/unhide translated/typesetting bar
- On-screen Japanese keyboard (hiragana/katakana)
- Automatic fit to window zoom during editing
- Mass export translated images in different filetypes
- Import all settings from previous project to new project

All I can come up with at the moment. On a different note, what does this do?
"Output setting -> export images using large image mode by default"

All in all, thank you for providing this invaluable piece of software. The combination of your program with the integration of other software from around the web and your immediate informative replies to user concerns is simply unmatched. I look forward to your upcoming plans and program refinements.

**Comment by xulihang** [comment] 2023-09-06 03:57
Thanks for the feedback. I will try to improve the software.

**Comment by xulihang** [comment] 2023-09-06 03:58
I've closed this issue. I will open new issues relating to your request.

**Closed** 2023-09-06 03:58 UTC

**Comment by xulihang** [comment] 2023-09-16 06:16
The default output format can be set to PNG in v2.4.1.

**Comment by xulihang** [comment] 2023-10-01 04:04
v2.5.2 solved the problem of loading large images in the mask editor.
