### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by Khado77** [xulihang/ImageTrans-docs#630] opened 2024-04-22 14:15 UTC
You can't set up any Hotkeys and they don't work.

**Comment by xulihang** [comment] 2024-04-22 14:32
What is your operating system and the system's language? The hotkeys work fine for me.

**Comment by Khado77** [comment] 2024-04-22 16:03
Windows 11 and my system language is german and I use english in ImageTrans.
For example If I want to set a Hotkey for Detect Ballons, I can't set the Hotkey to "1" or smth.
Only F1 and other Fx keys can be set up, but If you press the specific Hotkey, it won't work.

Try set up the Hotkey for "Detect Ballons" and try to use it.
It doesn't work for me.

**Comment by xulihang** [comment] 2024-04-23 01:28
The shortcuts have to be triggered with a modifier key like CTRL and ALT. Currently, you cannot assign a shortcut like 1.

**Comment by xulihang** [comment] 2024-04-23 01:31
You can set `Ctrl+1` for balloon detection. This should work.

![image](https://github.com/xulihang/ImageTrans-docs/assets/5462205/6454cddc-2840-47a2-88ed-9b4f747fc196)

The shortcut key setter has a problem processing the value of numbers.

**Comment by Khado77** [comment] 2024-04-23 02:15
I will try that with CTRL + key.

Also if you change the other shortcuts so that you can set up Detect Ballons to F1, then nothing happens when you press F1

**Comment by xulihang** [comment] 2024-04-23 02:27
Setting function keys as shortcuts for other operations does not work. This is a known issue.

**Comment by Khado77** [comment] 2024-04-23 02:45
So currently it only works if you set the hotkeys in a combination like CTRL + key which isn't used already, right?

**Comment by xulihang** [comment] 2024-04-23 03:15
Right. But you can override other shortcuts which are not using a function key.

**Comment by Khado77** [comment] 2024-04-23 03:47
Alright, I hope that you can fix the bug with the function keys. Would be nice to use one key instead of combinations.

**Comment by xulihang** [comment] 2024-06-23 06:35
I figured out why setting the function keys did not work. It is because the key has been bound to another menu item.

The problem is now fixed in v3.2.0.

**Closed** 2024-06-23 06:36 UTC

**Comment by Khado77** [comment] 2024-06-23 13:46
Is it possible that you can extend by purchase for v3.2.0?
My purchase seems to be expired for v3.2.0 but I would like to use the
function keys.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am So., 23. Juni 2024 um 08:36 Uhr schrieb Lihang Xu <
***@***.***>:

**Comment by xulihang** [comment] 2024-06-23 15:15
You can send me an email to get a discount to extend it.

**Comment by xulihang** [comment] 2024-06-23 15:22
Just purchase it again on FastSpring with a coupon code. A 60% off discount: 18.9 * 0.4 = $7.5

**Comment by xulihang** [comment] 2024-06-23 15:22
Then verify it with the new order id.

**Comment by xulihang** [comment] 2024-06-23 15:34
Okay. Please send an email to admin@basiccat.org
